check if the given file already exists and skip uploading.

diff --git a/bin/keeper-upload b/bin/keeper-upload
--- a/bin/keeper-upload
+++ b/bin/keeper-upload
@@ -1,4 +1,24 @@
 #!/bin/sh
 
-curl --silent -D - -F file=@$1 $KEEPER_SERVER | grep Location
 
+input_file=$1
+
+if [[ -z "$KEEPER_SERVER" ]]; then
+    echo "Set KEEPER_SERVER properly to use this program."
+    exit 1
+fi
+
+if [[ -f $input_file ]]; then
+    bin_dir=$(dirname $0)
+    input_file_basename=$(basename $input_file)
+    input_file_digest=$( ${bin_dir}/keeper-sha1sum-base64 $input_file | cut -f1 )
+
+    if [[ "200" == $(curl --silent -w "%{http_code}" -o /dev/null "${KEEPER_SERVER}/_exists/${input_file_digest}") ]]; then
+        echo "Location: ${KEEPER_SERVER}/${input_file_digest}/${input_file_basename}"
+    else
+        curl --silent -D - -F file=@$1 $KEEPER_SERVER | grep Location
+    fi
+else
+    echo "ERROR: File $input_file not found"
+    exit 1
+fi
